### PR TITLE
Update Clojure to 1.7.0

### PR DESCRIPTION
**Pull request by jstepien**
Clojure 1.7.0 does no longer intern symbols' and keywords' namespace
or name strings. Ruby.fastNewSymbol expects its argument to be interned.
This broke rubyization of Clojure keywords. This commit fixes it by
replacing a call to fastNewSymbol with newSymbol.

### CODE REVIEW

**Comment by mknoszlig** [comment]
thanks!

**Comment by ifesdjeen** [comment]
:+1:

**Comment by ifesdjeen** [comment]
do you have rights to push it to clojars and rubygems.org?

**Comment by mknoszlig** [comment]
hm, not sure, honestly - could you please bump and make a new release?

**Comment by ifesdjeen** [comment]
Sure

**Pull request merged**
