### PR TITLE
Clojure 1.8

### PR DESCRIPTION
**Pull request by cgore**

### CODE REVIEW

**Comment by ifesdjeen** [comment]
Thank you!

**Comment by cgore** [comment]
Thanks for merging it!
Can we get a build of this soon though?

**Comment by ifesdjeen** [comment]
Sure, we can release a new one tonight. I somehow did not think of it. Meanwhile, you could just use `exclude`in leiningen/maven

**Comment by cgore** [comment]
Cool, thanks!

**Pull request merged**
